import { BiodataProfile } from './types';

export const defaultBiodata: BiodataProfile = {
  fullName: '',
  gender: 'Male',
  dateOfBirth: '',
  age: '',
  height: '',
  bloodGroup: '',
  birthTime: '',
  birthPlace: '',
  complexion: '',
  gotra: '',
  devak: '',
  fatherName: '',
  fatherOccupation: '',
  motherName: '',
  motherOccupation: '',
  brothersMarried: '0',
  brothersUnmarried: '0',
  sistersMarried: '0',
  sistersUnmarried: '0',
  familyType: 'Nuclear',
  nativePlace: '',
  caste: '',
  subCaste: '',
  highestQualification: '',
  profession: '',
  companyName: '',
  annualIncome: '',
  workLocation: '',
  rashi: '',
  nakshatra: '',
  nadi: '',
  gan: '',
  mangal: 'No',
  expectedEducation: '',
  expectedHeightMin: '',
  expectedHeightMax: '',
  expectedCaste: '',
  preferredLocation: '',
  mobileNumber: '',
  parentContact: '',
  email: '',
  address: '',
  aboutMe: '',
  profilePhoto: '',
};
